# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2009-2025, by Samuel Williams.

require "xrb/parsers"
require "xrb/entities"
require "xrb/strings"
require "xrb/tag"

module Utopia
	module Content
		Tag = XRB::Tag
		
		# A hash which forces all keys to be symbols and fails with KeyError when strings are used.
		class SymbolicHash < Hash
			# Fetch a value using a symbolic key.
			# @parameter key [String | Symbol] The lookup key.
			# @returns [Object | nil] The associated value.
			# @raises [KeyError] If `key` is a string.
			def [] key
				raise KeyError.new("attribute #{key} is a string, prefer a symbol") if key.is_a? String
				super key.to_sym
			end
			
			# Assign a value after coercing its key to a symbol.
			# @parameter key [String | Symbol] The lookup key.
			# @parameter value [Object] The value to assign.
			# @returns [Object] The assigned value.
			def []= key, value
				super key.to_sym, value
			end
			
			# Fetch a value after coercing the key to a symbol.
			# @parameter key [String | Symbol] The lookup key.
			# @parameter arguments [Array] The arguments.
			# @yields {|key| ...} The missing symbolic key when no default argument is given.
			# @returns [Object] The associated, default, or block-provided value.
			def fetch(key, *arguments, &block)
				key = key.to_sym
				
				super
			end
			
			# Check whether this collection includes the given value.
			# @parameter key [String | Symbol] The lookup key.
			# @returns [Boolean] Whether the symbolic key exists.
			def include? key
				key = key.to_sym
				
				super
			end
		end
		
		# Provides a high level interface for parsing markup.
		class MarkupParser
			# A tag generated by parsing markup.
			class ParsedTag
				# Initialize a parsed opening tag at a source offset.
				# @parameter name [String] The name.
				# @parameter offset [Integer] The source offset.
				def initialize(name, offset)
					@offset = offset
					@tag = Tag.new(name, false, SymbolicHash.new)
				end
				
				attr :tag
				attr :offset
				
				# Convert this object to a string.
				# @returns [String] The resulting string.
				def to_s
					"<#{@tag.name}#{@tag.attributes.empty? ? '' : ' ...'}>"
				end
			end
			
			# The name of a closing tag fails to match up with the corresponding opening tag.
			class UnbalancedTagError < StandardError
				# Initialize an error for mismatched source tags.
				# @parameter buffer [String] The markup source buffer.
				# @parameter opening_tag [Object] The opening tag token.
				# @parameter closing_tag [Object] The closing tag token.
				def initialize(buffer, opening_tag, closing_tag = nil)
					@buffer = buffer
					@opening_tag = opening_tag
					@closing_tag = closing_tag
				end
				
				attr :buffer
				attr :opening_tag
				attr :closing_tag
				
				# Locate the opening tag in the source buffer.
				# @returns [XRB::Location] The opening tag location.
				def start_location
					XRB::Location.new(@buffer.read, opening_tag.offset)
				end
				
				# Locate the closing tag in the source buffer.
				# @returns [XRB::Location | nil] The closing tag location.
				def end_location
					if closing_tag and closing_tag.respond_to? :offset
						XRB::Location.new(@buffer.read, closing_tag.offset)
					end
				end
				
				# Convert this object to a string.
				# @returns [String] The resulting string.
				def to_s
					if @closing_tag
						"#{start_location}: #{@opening_tag} was not closed!"
					else
						"#{start_location}: #{@opening_tag} was closed by #{@closing_tag}!"
					end
				end
			end
			
			# Parse markup events into a delegate.
			# @parameter buffer [String | XRB::Buffer] The markup source buffer.
			# @parameter delegate [Object] The delegate.
			# @parameter entities [Hash] The named entity mappings.
			# @returns [nil] Parsing completes through delegate callbacks.
			# @raises [UnbalancedTagError] If the markup contains mismatched tags.
			def self.parse(buffer, delegate, entities = XRB::Entities::HTML5)
				# This is for compatibility with the existing API which passes in a string:
				buffer = XRB::Buffer(buffer)
				
				self.new(buffer, delegate, entities).parse!
			end
			
			# Initialize a streaming markup parser and its delegate.
			# @parameter buffer [String] The markup source buffer.
			# @parameter delegate [Object] The delegate.
			# @parameter entities [Hash] The named entity mappings.
			def initialize(buffer, delegate, entities = XRB::Entities::HTML5)
				@buffer = buffer
				
				@delegate = delegate
				@entities = entities
				
				@current = nil
				@stack = []
			end
			
			# Parse the markup buffer into delegate callbacks and validate balanced tags.
			# @returns [nil] Parsing completes through delegate callbacks.
			def parse!
				XRB::Parsers.parse_markup(@buffer, self, @entities)
				
				if tag = @stack.pop
					raise UnbalancedTagError.new(@buffer, tag)
				end
			end
			
			# Begin collecting an opening tag.
			# @parameter name [String] The name.
			# @parameter offset [Integer] The source offset.
			# @returns [ParsedTag] The tag being collected.
			def open_tag_begin(name, offset)
				@current = ParsedTag.new(name, offset)
			end
			
			# Process a markup attribute.
			# @parameter key [String | Symbol] The lookup key.
			# @parameter value [Object] The value to assign.
			# @returns [Object] The assigned attribute value.
			def attribute(key, value)
				@current.tag.attributes[key] = value
			end
			
			# Complete an opening tag and dispatch it to the delegate.
			# @parameter self_closing [Boolean] Whether the tag is self-closing.
			# @returns [nil] The current tag is cleared.
			def open_tag_end(self_closing)
				if self_closing
					@current.tag.closed = true
					@delegate.tag_complete(@current.tag)
				else
					@stack << @current
					@delegate.tag_begin(@current.tag)
				end
				
				@current = nil
			end
			
			# Process a closing markup tag.
			# @parameter name [String] The name.
			# @parameter offset [Integer] The source offset.
			# @returns [Object] The delegate's tag-end result.
			# @raises [UnbalancedTagError] If the closing tag does not match its opening tag.
			def close_tag(name, offset)
				@current = @stack.pop
				tag = @current.tag
				
				if tag.name != name
					raise UnbalancedTagError.new(@buffer, @current, ParsedTag.new(name, offset))
				end
				
				@delegate.tag_end(tag)
			end
			
			# Process a document type declaration.
			# @parameter string [String] The string.
			# @returns [Object] The delegate's write result.
			def doctype(string)
				@delegate.write(string)
			end
			
			# Process a markup comment.
			# @parameter string [String] The string.
			# @returns [Object] The delegate's write result.
			def comment(string)
				@delegate.write(string)
			end
			
			# Process a markup instruction.
			# @parameter string [String] The string.
			# @returns [Object] The delegate's write result.
			def instruction(string)
				@delegate.write(string)
			end
			
			# Process a CDATA section.
			# @parameter string [String] The string.
			# @returns [Object] The delegate's write result.
			def cdata(string)
				@delegate.write(string[9..-4])
			end
			
			# Process text content.
			# @parameter string [String] The string.
			# @returns [Object] The delegate's text result.
			def text(string)
				@delegate.text(string)
			end
		end
	end
end
