# frozen_string_literal: true

source 'https://rubygems.org'

gem 'utopia', '~> $UTOPIA_VERSION'
# gem 'utopia-gallery'
# gem 'utopia-analytics'

gem 'rake'
gem 'bake'
gem 'bundler'

gem 'rack-test'

group :development do
	# For `rake server`:
	gem 'guard-falcon', require: false
	gem 'guard-rspec', require: false
	
	# For `rspec` testing:
	gem 'rspec'
	gem 'covered'
	
	gem 'async-rspec'
	gem 'benchmark-http'
end

group :production do
	gem 'falcon'
end
