
source "https://rubygems.org"

gem "utopia", "~> $UTOPIA_VERSION"
# gem "utopia-tags-gallery"
# gem "utopia-tags-google-analytics"

gem "rake"
gem "bundler"

group :development do
	# For `rake server`:
	gem "puma"
	
	# For `rake console`:
	gem "pry"
	gem "rack-test"
end

group :production do
	# Used for passenger-config to restart server after deployment:
	gem "passenger"
end
