
desc 'Run by git post-update hook when deployed to a web server'
task :deploy do
	# This task is typiclly run after the site is updated but before the server is restarted.
	puts "Preparing to deploy site in #{Dir.pwd.inspect}..."
end

desc 'Set up the environment for running your web application'
task :environment do
	RACK_ENV = (ENV['RACK_ENV'] ||= 'development').to_sym
end

desc 'Run a server for testing your web application'
task :server => :environment do
	system('puma')
end

desc 'Start an interactive console for your web application'
task :console => :environment do
	require 'pry'
	require 'rack/test'
	
	include Rack::Test::Methods
	
	def app
		@app ||= Rack::Builder.parse_file(File.expand_path("config.ru", __dir__)).first
	end
	
	Pry.start
end

task :default => :server
