
source "https://rubygems.org"

gem "utopia", path: File.expand_path("../", __dir__)

gem "rack-freeze", "~> 1.2"

gem "rake"
gem "bundler"

gem "kramdown"
gem "kramdown-parser-gfm"

group :development do
	# For `rake server`:
	gem "guard-falcon"
	gem "falcon"
	
	# For `rake console`:
	gem "pry"
	gem "rack-test"
	
	# For `rspec` testing:
	gem "rspec"
end
