
source "https://rubygems.org"

gem "utopia", path: File.expand_path("../", __dir__)

gem "rake"
gem "bundler"

gem "kramdown"

group :development do
	# For `rake server`:
	gem "puma"
	
	# For `rake console`:
	gem "pry"
	gem "rack-test"
	
	# For `rspec` testing:
	gem "rspec"
	gem "simplecov"
end

group :production do
	# Used for passenger-config to restart server after deployment:
	gem "passenger"
end
