# frozen_string_literal: true

source "https://rubygems.org"

gem "utopia", path: File.expand_path("../", __dir__)

gem "rake"
gem "bundler"

gem "kramdown"
gem "kramdown-parser-gfm"

group :development do
	gem "guard-falcon"
	gem "falcon"
	
	gem "rack-test"
	gem "rspec"
end
