name: Test External

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
        apt-get: libvips
        brew: vips
    
    - name: Run tests
      timeout-minutes: 10
      run: bundle exec bake test:external
