name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        
        experimental: [false]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Installing packages (ubuntu)
      if: matrix.os == 'ubuntu'
      run: sudo apt-get install wget
    
    - name: Installing packages (macos)
      if: matrix.os == 'macos'
      run: brew install wget
    
    - name: Run tests
      timeout-minutes: 10
      run: |
        git config --global user.email "samuel@oriontransfer.net"
        git config --global user.name "Samuel Williams"
        git config --global init.defaultBranch main
        bundle exec bake test
